/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as AiAssistantRouteImport } from './routes/ai-assistant'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AutomationAgentRouteImport } from './routes/automation-agent'
import { Route as AutomationRulesRouteImport } from './routes/automation-rules'
import { Route as BatchesRouteImport } from './routes/batches'
import { Route as CandidatesRouteImport } from './routes/candidates'
import { Route as CommunicationsRouteImport } from './routes/communications'
import { Route as EmailAutomationRouteImport } from './routes/email-automation'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NeedsAttentionRouteImport } from './routes/needs-attention'
import { Route as QueriesRouteImport } from './routes/queries'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SimulatorRouteImport } from './routes/simulator'
import { Route as TeamRouteImport } from './routes/team'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as BatchesIndexRouteImport } from './routes/batches.index'
import { Route as BatchesBatchIdRouteImport } from './routes/batches.$batchId'
import { Route as BatchesNewRouteImport } from './routes/batches.new'
import { Route as CandidatesIndexRouteImport } from './routes/candidates.index'
import { Route as CandidatesCandidateIdRouteImport } from './routes/candidates.$candidateId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAssistantRoute = AiAssistantRouteImport.update({
  id: '/ai-assistant',
  path: '/ai-assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationAgentRoute = AutomationAgentRouteImport.update({
  id: '/automation-agent',
  path: '/automation-agent',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationRulesRoute = AutomationRulesRouteImport.update({
  id: '/automation-rules',
  path: '/automation-rules',
  getParentRoute: () => rootRouteImport,
} as any)
const BatchesRoute = BatchesRouteImport.update({
  id: '/batches',
  path: '/batches',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatesRoute = CandidatesRouteImport.update({
  id: '/candidates',
  path: '/candidates',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunicationsRoute = CommunicationsRouteImport.update({
  id: '/communications',
  path: '/communications',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailAutomationRoute = EmailAutomationRouteImport.update({
  id: '/email-automation',
  path: '/email-automation',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NeedsAttentionRoute = NeedsAttentionRouteImport.update({
  id: '/needs-attention',
  path: '/needs-attention',
  getParentRoute: () => rootRouteImport,
} as any)
const QueriesRoute = QueriesRouteImport.update({
  id: '/queries',
  path: '/queries',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulatorRoute = SimulatorRouteImport.update({
  id: '/simulator',
  path: '/simulator',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const BatchesIndexRoute = BatchesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BatchesRoute,
} as any)
const BatchesBatchIdRoute = BatchesBatchIdRouteImport.update({
  id: '/$batchId',
  path: '/$batchId',
  getParentRoute: () => BatchesRoute,
} as any)
const BatchesNewRoute = BatchesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => BatchesRoute,
} as any)
const CandidatesIndexRoute = CandidatesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CandidatesRoute,
} as any)
const CandidatesCandidateIdRoute = CandidatesCandidateIdRouteImport.update({
  id: '/$candidateId',
  path: '/$candidateId',
  getParentRoute: () => CandidatesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/analytics': typeof AnalyticsRoute
  '/automation-agent': typeof AutomationAgentRoute
  '/automation-rules': typeof AutomationRulesRoute
  '/batches': typeof BatchesRouteWithChildren
  '/candidates': typeof CandidatesRouteWithChildren
  '/communications': typeof CommunicationsRoute
  '/email-automation': typeof EmailAutomationRoute
  '/integrations': typeof IntegrationsRoute
  '/login': typeof LoginRoute
  '/needs-attention': typeof NeedsAttentionRoute
  '/queries': typeof QueriesRoute
  '/settings': typeof SettingsRoute
  '/simulator': typeof SimulatorRoute
  '/team': typeof TeamRoute
  '/templates': typeof TemplatesRoute
  '/batches/$batchId': typeof BatchesBatchIdRoute
  '/batches/new': typeof BatchesNewRoute
  '/candidates/$candidateId': typeof CandidatesCandidateIdRoute
  '/batches/': typeof BatchesIndexRoute
  '/candidates/': typeof CandidatesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/analytics': typeof AnalyticsRoute
  '/automation-agent': typeof AutomationAgentRoute
  '/automation-rules': typeof AutomationRulesRoute
  '/communications': typeof CommunicationsRoute
  '/email-automation': typeof EmailAutomationRoute
  '/integrations': typeof IntegrationsRoute
  '/login': typeof LoginRoute
  '/needs-attention': typeof NeedsAttentionRoute
  '/queries': typeof QueriesRoute
  '/settings': typeof SettingsRoute
  '/simulator': typeof SimulatorRoute
  '/team': typeof TeamRoute
  '/templates': typeof TemplatesRoute
  '/batches/$batchId': typeof BatchesBatchIdRoute
  '/batches/new': typeof BatchesNewRoute
  '/candidates/$candidateId': typeof CandidatesCandidateIdRoute
  '/batches': typeof BatchesIndexRoute
  '/candidates': typeof CandidatesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/analytics': typeof AnalyticsRoute
  '/automation-agent': typeof AutomationAgentRoute
  '/automation-rules': typeof AutomationRulesRoute
  '/batches': typeof BatchesRouteWithChildren
  '/candidates': typeof CandidatesRouteWithChildren
  '/communications': typeof CommunicationsRoute
  '/email-automation': typeof EmailAutomationRoute
  '/integrations': typeof IntegrationsRoute
  '/login': typeof LoginRoute
  '/needs-attention': typeof NeedsAttentionRoute
  '/queries': typeof QueriesRoute
  '/settings': typeof SettingsRoute
  '/simulator': typeof SimulatorRoute
  '/team': typeof TeamRoute
  '/templates': typeof TemplatesRoute
  '/batches/$batchId': typeof BatchesBatchIdRoute
  '/batches/new': typeof BatchesNewRoute
  '/candidates/$candidateId': typeof CandidatesCandidateIdRoute
  '/batches/': typeof BatchesIndexRoute
  '/candidates/': typeof CandidatesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/ai-assistant'
    | '/analytics'
    | '/automation-agent'
    | '/automation-rules'
    | '/batches'
    | '/candidates'
    | '/communications'
    | '/email-automation'
    | '/integrations'
    | '/login'
    | '/needs-attention'
    | '/queries'
    | '/settings'
    | '/simulator'
    | '/team'
    | '/templates'
    | '/batches/$batchId'
    | '/batches/new'
    | '/candidates/$candidateId'
    | '/batches/'
    | '/candidates/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/ai-assistant'
    | '/analytics'
    | '/automation-agent'
    | '/automation-rules'
    | '/communications'
    | '/email-automation'
    | '/integrations'
    | '/login'
    | '/needs-attention'
    | '/queries'
    | '/settings'
    | '/simulator'
    | '/team'
    | '/templates'
    | '/batches/$batchId'
    | '/batches/new'
    | '/candidates/$candidateId'
    | '/batches'
    | '/candidates'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/ai-assistant'
    | '/analytics'
    | '/automation-agent'
    | '/automation-rules'
    | '/batches'
    | '/candidates'
    | '/communications'
    | '/email-automation'
    | '/integrations'
    | '/login'
    | '/needs-attention'
    | '/queries'
    | '/settings'
    | '/simulator'
    | '/team'
    | '/templates'
    | '/batches/$batchId'
    | '/batches/new'
    | '/candidates/$candidateId'
    | '/batches/'
    | '/candidates/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  AiAssistantRoute: typeof AiAssistantRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AutomationAgentRoute: typeof AutomationAgentRoute
  AutomationRulesRoute: typeof AutomationRulesRoute
  BatchesRoute: typeof BatchesRouteWithChildren
  CandidatesRoute: typeof CandidatesRouteWithChildren
  CommunicationsRoute: typeof CommunicationsRoute
  EmailAutomationRoute: typeof EmailAutomationRoute
  IntegrationsRoute: typeof IntegrationsRoute
  LoginRoute: typeof LoginRoute
  NeedsAttentionRoute: typeof NeedsAttentionRoute
  QueriesRoute: typeof QueriesRoute
  SettingsRoute: typeof SettingsRoute
  SimulatorRoute: typeof SimulatorRoute
  TeamRoute: typeof TeamRoute
  TemplatesRoute: typeof TemplatesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-assistant': {
      id: '/ai-assistant'
      path: '/ai-assistant'
      fullPath: '/ai-assistant'
      preLoaderRoute: typeof AiAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automation-agent': {
      id: '/automation-agent'
      path: '/automation-agent'
      fullPath: '/automation-agent'
      preLoaderRoute: typeof AutomationAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automation-rules': {
      id: '/automation-rules'
      path: '/automation-rules'
      fullPath: '/automation-rules'
      preLoaderRoute: typeof AutomationRulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/batches': {
      id: '/batches'
      path: '/batches'
      fullPath: '/batches'
      preLoaderRoute: typeof BatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidates': {
      id: '/candidates'
      path: '/candidates'
      fullPath: '/candidates'
      preLoaderRoute: typeof CandidatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communications': {
      id: '/communications'
      path: '/communications'
      fullPath: '/communications'
      preLoaderRoute: typeof CommunicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email-automation': {
      id: '/email-automation'
      path: '/email-automation'
      fullPath: '/email-automation'
      preLoaderRoute: typeof EmailAutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/needs-attention': {
      id: '/needs-attention'
      path: '/needs-attention'
      fullPath: '/needs-attention'
      preLoaderRoute: typeof NeedsAttentionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queries': {
      id: '/queries'
      path: '/queries'
      fullPath: '/queries'
      preLoaderRoute: typeof QueriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulator': {
      id: '/simulator'
      path: '/simulator'
      fullPath: '/simulator'
      preLoaderRoute: typeof SimulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/batches/': {
      id: '/batches/'
      path: '/'
      fullPath: '/batches/'
      preLoaderRoute: typeof BatchesIndexRouteImport
      parentRoute: typeof BatchesRoute
    }
    '/batches/$batchId': {
      id: '/batches/$batchId'
      path: '/$batchId'
      fullPath: '/batches/$batchId'
      preLoaderRoute: typeof BatchesBatchIdRouteImport
      parentRoute: typeof BatchesRoute
    }
    '/batches/new': {
      id: '/batches/new'
      path: '/new'
      fullPath: '/batches/new'
      preLoaderRoute: typeof BatchesNewRouteImport
      parentRoute: typeof BatchesRoute
    }
    '/candidates/': {
      id: '/candidates/'
      path: '/'
      fullPath: '/candidates/'
      preLoaderRoute: typeof CandidatesIndexRouteImport
      parentRoute: typeof CandidatesRoute
    }
    '/candidates/$candidateId': {
      id: '/candidates/$candidateId'
      path: '/$candidateId'
      fullPath: '/candidates/$candidateId'
      preLoaderRoute: typeof CandidatesCandidateIdRouteImport
      parentRoute: typeof CandidatesRoute
    }
  }
}

interface BatchesRouteChildren {
  BatchesBatchIdRoute: typeof BatchesBatchIdRoute
  BatchesNewRoute: typeof BatchesNewRoute
  BatchesIndexRoute: typeof BatchesIndexRoute
}

const BatchesRouteChildren: BatchesRouteChildren = {
  BatchesBatchIdRoute: BatchesBatchIdRoute,
  BatchesNewRoute: BatchesNewRoute,
  BatchesIndexRoute: BatchesIndexRoute,
}

const BatchesRouteWithChildren =
  BatchesRoute._addFileChildren(BatchesRouteChildren)

interface CandidatesRouteChildren {
  CandidatesCandidateIdRoute: typeof CandidatesCandidateIdRoute
  CandidatesIndexRoute: typeof CandidatesIndexRoute
}

const CandidatesRouteChildren: CandidatesRouteChildren = {
  CandidatesCandidateIdRoute: CandidatesCandidateIdRoute,
  CandidatesIndexRoute: CandidatesIndexRoute,
}

const CandidatesRouteWithChildren = CandidatesRoute._addFileChildren(
  CandidatesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  AiAssistantRoute: AiAssistantRoute,
  AnalyticsRoute: AnalyticsRoute,
  AutomationAgentRoute: AutomationAgentRoute,
  AutomationRulesRoute: AutomationRulesRoute,
  BatchesRoute: BatchesRouteWithChildren,
  CandidatesRoute: CandidatesRouteWithChildren,
  CommunicationsRoute: CommunicationsRoute,
  EmailAutomationRoute: EmailAutomationRoute,
  IntegrationsRoute: IntegrationsRoute,
  LoginRoute: LoginRoute,
  NeedsAttentionRoute: NeedsAttentionRoute,
  QueriesRoute: QueriesRoute,
  SettingsRoute: SettingsRoute,
  SimulatorRoute: SimulatorRoute,
  TeamRoute: TeamRoute,
  TemplatesRoute: TemplatesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
